name: Smoke test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Run Checks
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features
  clippy:
    runs-on: ubuntu-latest
    name: Run Clippy
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings
  rust-fmt:
    runs-on: ubuntu-latest
    name: Run Rustfmt
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
  examples:
    runs-on: ubuntu-latest
    name: Run examples
    steps:
    - name: Install minimal stable toolchain with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install foundationdb-clients
      run: wget https://github.com/apple/foundationdb/releases/download/7.1.25/foundationdb-clients_7.1.25-1_amd64.deb && sudo dpkg -i foundationdb-clients_7.1.25-1_amd64.deb
    - uses: actions/checkout@v3
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - name: Run examples
      run: cargo run --example select
